#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2009 Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# This script is designed for development use only.  To run the EPICS IOC
# normally, install it using the command
#
#   ./install_d/libera-install-ioc -af <options>
#
# and start it with the command
#
#   /etc/init.d/libera-driver start

echo Running Libera EPICS ioc in test mode

cd "$(dirname "$0")"
SOURCE="$(pwd)"
. scripts/architecture
CONFIGDIR=$CONFIGDIR exec ./scripts/runioc "$@"
