#!/bin/sh

. /etc/init.d/functions

run_daemon()
{
    while :; do
        # Wait until tomorrow
        sleep 86400

        # Clean all the RX overrun crap out of /var/run/debug
        /etc/init.d/sysklogd stop
        sleep 1
        grep -v 'kernel: eth0: RX overrun\|last message repeated' \
            /var/log/debug >/var/log/debug~
        mv /var/log/debug~ /var/log/debug
        /etc/init.d/sysklogd start
    done
}

case "$1" in
    start)
        echo -n 'Starting debug cleaning daemon...'
        if [ -e /var/run/clean-debug.pid ]; then
            echo -n 'already running?'
            false
            evaluate_retval
        else
            run_daemon </dev/null >/dev/null 2>&1 &
            evaluate_retval
            echo $! >/var/run/clean-debug.pid
        fi
        ;;
    stop)
        echo -n 'Stopping debug cleaning daemon...'
        kill $(cat /var/run/clean-debug.pid)
        evaluate_retval
        rm -f  /var/run/clean-debug.pid
        ;;
    *)  echo "Usage: $0 {start|stop}"
esac
