#!/bin/sh
# Retrieve PV from all liberas matching pattern.

NAME_LIST="$(dirname "$(readlink -fn "$0")")/allbpms"

MATCH="$1"
PV="$2"

caget -a -w5 $(
    for BPM in $(grep -E "$MATCH" "$NAME_LIST"); do
        echo "$BPM:$PV"
    done)
