#!/usr/bin/env dls-python2.6

from pkg_resources import require
require("cothread")
from cothread import catools

import re
import sys
import os


allbpms = os.path.join(os.path.dirname(__file__), 'allbpms')

pattern = re.compile(sys.argv[1])
pv = sys.argv[2]

bpms = [line[:-1] for line in file(allbpms) if pattern.search(line)]
pvs = ['%s:%s' % (bpm, pv) for bpm in bpms]

errorcode = 0
for v in catools.caget(pvs, timeout = 2, throw = False):
    if v.ok:
        print v.name, v
    else:
        print >>sys.stderr, v.name, v
        errorcode = 1
sys.exit(errorcode)
