#!/usr/bin/env dls-python

from pkg_resources import require
require("cothread")
from cothread import catools

import re
import sys
import os


allbpms = os.path.join(os.path.dirname(__file__), 'allbpms')

pattern = re.compile(sys.argv[1])
pv = sys.argv[2]
value = sys.argv[3]

bpms = [line[:-1] for line in file(allbpms) if pattern.search(line)]
pvs = ['%s:%s' % (bpm, pv) for bpm in bpms]

errorcode = 0
for s in catools.caput(pvs, value, timeout = 2, throw = False):
    if not s:
        print >>sys.stderr, s.name, s
        errorcode = 1
sys.exit(errorcode)
