#!/bin/sh

# Script for checking synchronisation state for all SR liberas.

LOG_FILE="$(mktemp /tmp/SR-sync.check.XXXXXX)"

echo Switching EVRs into Synchronised mode: $(
    for n in $(seq -f%02g 24); do
        caput -t SR${n}C-DI-EVR-01:TRIG:MODE Synchronised
    done |
    sort |
    uniq )

sleep 1

echo Arming Get-Time:
liberas SR 'echo $(hostname) $(/opt/bin/libera -apt0 1 2>&1 >/dev/null)' |
    cat >$LOG_FILE &
LIBERAS_ID=$!

echo Waiting 10s for all Liberas to arm:
SPINNER='\|/-'
for ((i = 0; i < 20; i++)); do
    echo -n ${SPINNER:$((i%4)):1} 
    echo -en '\r'
    sleep 0.5
done

echo Sending Get-Time event: $(
    caput -t LI-TI-MTGEN-01:SR-DI 1
    caput -t LI-TI-MTGEN-01:SR-DI 0 )

sleep 3

echo Restoring EVR normal mode: $(
    for n in $(seq -f%02g 24); do
        caput -t SR${n}C-DI-EVR-01:TRIG:MODE Normal
    done |
    sort |
    uniq )

echo
echo -n 'Checking for unlocked lmtd: '
liberas SR 'grep lmtd /var/log/messages |tail -n 1' | grep -v locked
echo Check complete

wait $LIBERAS_ID

RESPONSES=$(($(cat $LOG_FILE | wc -l)))
echo
if ((RESPONSES == 168)); then
    echo All liberas responded
else
    echo "Only $RESPONSES liberas responded (should be 168)"
fi

MC_CLOCKS="$(cut -d' ' -f3 $LOG_FILE  | sort | uniq)"
echo
echo 'Machine clock (expect one value): ' $MC_CLOCKS
echo
echo 'System times (expect within <1 microsecond):'
cut -d' ' -f5- $LOG_FILE |sort |uniq

if [ $(($(echo "$MC_CLOCKS" | wc -w))) == 1 ]; then
    rm $LOG_FILE
else
    echo
    echo Log file in $LOG_FILE
fi
