#!/bin/sh



# Turn normal triggers off and wait for this to take effect.
caput TS-DI-EVR-01:TRIG:MODE Synchronised
sleep 1

# First synchronise the machine clock.  This we do simply by allowing a
# normal trigger through.
echo
echo Synchronising machine clocks
echo
caput TS-DI-EBPM-01:CK:MC_SYNC_S 0
sleep 1
caput TS-DI-EVR-01:TRIG:MODE Normal
sleep 1
caput TS-DI-EVR-01:TRIG:MODE Synchronised
sleep 1


# Now synchronise the system clock.  This is more tricky, as we need to
# synchronise to the 1Hz heartbeat.
echo
echo Synchronising system clocks
echo
caput TS-DI-EBPM-01:CK:SC_SYNC_S 0
sleep 1
caput TS-DI-EVR-01:TS-RESET.OUT2 1
sleep 2


# Put everything back to normal when we're done.
caput TS-DI-EVR-01:TRIG:MODE Normal
echo Done.
