#!/bin/sh

VERSION=${1?Version to deploy}

ARGS=-fls

TARGET="${2:-/mnt/nfs/Libera/$VERSION}"
COMMAND="$TARGET/ioc/install/libera-install-ioc $ARGS"

liberas 'LB|BR|BS' $COMMAND BO
liberas 'SR'       $COMMAND SR
