#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2005-2007 Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

set -e

# Script to build the distribution, called thus:
#
#   distribute <version> <destination>
#
# The specified version (or the trunk, if requested) is built for
# distribution in <destination>.

VERSION="${1:?Which version to distribute?}"
TARGET="${2:?Where to put the distribution?}"

# Convert target into absolute path.
mkdir -p "$TARGET"  &&
TARGET="$(cd "$TARGET" && pwd)"

# Figure out the subversion source.  For testing pick up the trunk version.
if [ "$VERSION" = trunk ]; then
    SVN_SOURCE="$SVN_ROOT/diamond/trunk/ioc/Libera"
    # When building from trunk use the last changed revision to label which
    # version we're actually building.
    VERSION=trunk."$(
        svn info "$SVN_SOURCE" |
        sed -rn '/^Last Changed Rev: (.*)$/{s//\1/;p;}' )"
else
    SVN_SOURCE="$SVN_ROOT/diamond/release/ioc/Libera/$VERSION"
fi
LIBERA_VERSION=Libera-"$VERSION"

# Do all the work in a temporary directory
TEMP_ROOT="$(mktemp -d /tmp/distribute-libera.XXXXXX)"
trap 'rm -rf "$TEMP_ROOT"' EXIT

# Grab a pristine version of what we want to release.  
cd "$TEMP_ROOT"
svn export -q "$SVN_SOURCE" "$LIBERA_VERSION"
cd "$LIBERA_VERSION"

# Patch this release for public distribution.
# We remove docs because it's work in progress and contains crap right now.
# We remove dsc because it's not actually part of this distribution.
rm -rf docs system/dsc
# Make sure the distributed version doesn't try to build FF
sed -r -i 's/(^BUILD_FF_SUPPORT=).*$/\1no/' install/CONFIG

# Build the core distribution.  Note that we can't compress the tar file as
# we create it as we're going to need to add the prebuilt files afterwards.
TAR_FILE="$TARGET/libera-epics-$VERSION.tar"
tar cf "$TAR_FILE" -C.. "$LIBERA_VERSION"

# Now prepare the prebuilt files.
mkdir install/prebuilt
ln -s liberaApp/src dbd
for db in libera fastFeedback; do
    python2.4 liberaApp/Db/$db.py /dev/stdout |
        sed '/^# \*\*\* Please do not edit/d' >install/prebuilt/$db.db
done
for py in liberaApp/src/*.py; do
    python2.4 $py >install/prebuilt/$(basename $py .py).h
done

# Add the prebuilt files and finish off the distribution
tar rf "$TAR_FILE" -C.. "$LIBERA_VERSION/install/prebuilt"
gzip -f "$TAR_FILE"

echo "Distribution built ok in: $TAR_FILE.gz"
