#!/bin/sh

# This script is copied into $INSTALL_HOST and should be run in place on the
# IOC to ensure that the appropriate files are copied into place.

cd "$(dirname "$0")"

if [ "$(uname -m)" != armv5tel ]; then
    echo This should be run on Libera >&2
    exit 1
fi

# Ensure epics driver isn't running at the moment.
[ -e /var/run/ioc.pid ] && kill "$(cat /var/run/ioc.pid)"

# Copy over the local configuration files.
cp -f epics /etc/init.d
cp -f epics_ioc /etc/sysconfig

# Link the epics startup script in so that it automatically starts when the
# IOC is booted.
ln -sf ../init.d/epics /etc/rc3.d/S900epics
ln -sf ../init.d/epics /etc/rc6.d/K100epics

