#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2005  Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# Install a build IOC in the target IOC directory.

SOURCE="$(cd "$(dirname "$0")"/..; pwd)"  &&
if (($# > 0)); then
    INSTALL_HOST="$1"
else
    . "$SOURCE"/install/CONFIG  &&
    : ${INSTALL_HOST:?Local installation path not defined}
fi  &&
[ -d "$INSTALL_HOST" ]  &&

# Erase everything in the target directory: start from scratch on each
# install.
TARGET="$INSTALL_HOST"/ioc  &&
rm -rf "$TARGET"  &&

# First ensure the target directory structure exists
for dir in bin dbd db; do
    mkdir -p "$TARGET/$dir"
done  &&

# Copy over the appropriate components
cp "$SOURCE/bin/linux-arm"/* "$TARGET/bin"  &&
cp "$SOURCE/dbd"/* "$TARGET/dbd"  &&
cp "$SOURCE/db"/* "$TARGET/db"  &&

for f in runioc st.cmd; do
    cp "$SOURCE/install/$f" "$TARGET"
done  &&

# Also create installation support files.
mkdir -p "$TARGET"/install  &&

# Also place the ioc specific files ready to be deployed on the ioc.
for f in epics gain.conf libera-install-ioc offsets.conf; do
    cp "$SOURCE"/install/$f "$TARGET"/install
done  &&

# The epics_ioc file is basically a digest of the stuff in CONFIG that is
# directly relevant to the target system.  All symbols definitions starting
# IOC_ or xx_IOC_ will be passed through to the target IOC to configure
# run-time operation.
grep -E '^([[:alpha:]][[:alnum:]]_)?IOC_[[:alnum:]_]*=' \
    "$SOURCE"/install/CONFIG >>"$TARGET"/install/epics_ioc  &&

# Prepare the list of possible location names for use by libera-install-ioc.
# The set of location codes is determined by a simple pattern match, and we
# filter out the unique set of locations.
#    Locations are used in the CONFIG file to specify different configuration
# for different locations on the ring.
sed -n '/^\([[:alpha:]][[:alnum:]]\)_IOC_.*$/{s//\1/;p;}' \
    "$TARGET"/install/epics_ioc |
sort |
uniq >"$TARGET"/install/locations  &&


echo IOC installed in "$TARGET". 
