#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2005-2007 Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# Creates an intermediate installation directory: extracts all the files
# required for a complete installation from the current build.

set -e

# Files copied from install directory
INSTALL_FILES='
    CONFIG
    epics
    locations
    libera-install-fpga
    libera-install-ioc'


SOURCE="$(cd "$(dirname "$0")"/..; pwd)"  
. "$SOURCE"/install/CONFIG  
if (($# > 0)); then
    INSTALL_HOST="$1"
    FPGA_SOURCE="$2"
else
    : ${INSTALL_HOST:?Local installation path not defined}
fi  


# Erase everything in the target directory: start from scratch on each
# install.
TARGET="$INSTALL_HOST"/ioc  
rm -rf "$TARGET"
mkdir -p "$TARGET"

# Copy over the appropriate components
for dir in bin dbd db; do
    cp -r "$SOURCE/$dir" "$TARGET"
done

# Copy over the installation specific files into the install directory.
mkdir -p "$TARGET"/install  
for f in $INSTALL_FILES; do
    cp "$SOURCE"/install/$f "$TARGET"/install
done

# To be friendly create a redirector script to invoke the true runioc script.
# This is only intended for testing use.
cat <<'EOF' >"$TARGET/runioc"
#!/bin/sh
"$(dirname "$0")/bin/linux-arm/runioc" "$@"
EOF
chmod +x "$TARGET/runioc"


# Finally copy over the FPGA files
if [ -n "$FPGA_SOURCE" ]; then
    FPGA_VERSION="$(basename "$FPGA_SOURCE")"

    rm -rf "$INSTALL_HOST"/fpga
    mkdir "$INSTALL_HOST"/fpga
    cd "$FPGA_SOURCE"
    for f in *.dls*; do
        cp $f "$INSTALL_HOST"/fpga/$f."$FPGA_VERSION"
    done
fi


echo IOC installed in "$TARGET". 
