#!/bin/sh

# This script is copied into $INSTALL_HOST and should be run in place on the
# IOC to ensure that the appropriate files are copied into place.

cd "$(dirname "$0")"

if [ "$(uname -m)" != armv5tel ]; then
    echo This should be run on Libera >&2
    exit 1
fi

[ -e /etc/init.d/epics ] && [ -e /var/run/ioc ] && /etc/init.d/epics stop

cp -f epics /etc/init.d
cp -f epics_ioc /etc/sysconfig
ln -sf ../init.d/epics /etc/rc3.d/S900epics
ln -sf ../init.d/epics /etc/rc6.d/K100epics

