#!/bin/sh


# This file is part of the Libera EPICS Driver,
# Copyright (C) 2005  Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# This script is copied into $INSTALL_HOST and should be run in place on the
# IOC to ensure that the appropriate files are copied into place.
#
# This installation script supports two modes of operation of the installed
# IOC: testing (installed on the remote file system) or final (copied to the
# local file system).

SOURCE="$(cd "$(dirname "$0")"/..; pwd)"

function Error()
{
    echo >&2 "$@"
    exit 1
}

# Ensure this isn't run by accident on the development machine.
[ "$(uname -m)" != armv5tel ]  &&
    Error This should be run on Libera

# Parse local installation options
TARGET=none
while getopts 'fth' option; do
    case "$option" in
    f)  TARGET=final ;;
    t)  TARGET=test ;;
    h)  cat <<'EOF'
Usage: libera-install-ioc <option>
where <option> is one of
    -f  Final install: copy files to local /opt directory
    -t  Testing install: don't copy files, use from configured location
EOF
        exit 0 ;;
    *)  Error 'Invalid option: try -h for help' ;;
    esac
done
[ $TARGET == none ]  &&
    Error 'Specify installation option.  Try -h for help.'
(($# >= OPTIND))  &&
    Error 'Invalid arguments: try -h for help'

# Hard-wired targets on local file system
EPICS_TARGET=/opt/epics
IOC_TARGET=/opt/ioc
STATE_DIR=/opt/state

# Ensure epics driver isn't running at the moment.
if [ -e /var/run/ioc.pid ]; then
    kill "$(cat /var/run/ioc.pid)"
    rm -f /var/run/ioc.pid
fi

# Ensure the state directory exists (but don't interfere with it!)
mkdir -p "$STATE_DIR"  &&

# If final installation selected then copy over all the run-time files and
# update the configuration file to point to them.
if [ $TARGET == final ]; then
    # Copy over all the runtime files.  First make sure the target directory
    # is fresh.
    rm -rf "$IOC_TARGET"  &&
    umask 22  &&
    mkdir -p "$IOC_TARGET"  &&
    cp -r "$SOURCE"/* "$IOC_TARGET"  &&
    rm -rf "$IOC_TARGET"/install  &&

    # Hack the configuration file so that it now points to the standard
    # locations.  This allows a smooth transition from testing mode to release
    # mode, but does make the use of CONFIG rather confused.  This is bound to
    # change soon...
    sed <"$SOURCE"/install/epics_ioc >/etc/sysconfig/epics_ioc '
        /^EPICS_BASE=/s:=.*$:="'"$EPICS_TARGET"'":
        /^LIBERA_IOC=/s:=.*$:="'"$IOC_TARGET"'/runioc":
        /^IOC_STATE_PATH=/s:=.*$:="'"$STATE_DIR"'":
    '
else
    # Just place the unmodified configuration file in place.
    cp "$SOURCE"/install/epics_ioc /etc/sysconfig/epics_ioc
fi  &&

# Copy the startup script
cp -f "$SOURCE"/install/epics /etc/init.d  &&
# Link the epics startup script in so that it automatically starts when the
# IOC is booted.
ln -sf ../init.d/epics /etc/rc3.d/S900epics  &&
ln -sf ../init.d/epics /etc/rc6.d/K100epics  

