#!/bin/sh

# Hard-wired path to synclibera.  Hard to find a better location for this, as
# it's no longer part of core Libera.
SYNC_LIBERA_PATH=/home/mga83/epics/diagOpi/scripts

cd "$(dirname "$(readlink -fn "$0")")"

PATH="$(pwd)"/scripts:"$PATH":"$SYNC_LIBERA_PATH"

export EPICS_CA_MAX_ARRAY_BYTES=1000000
exec edm -x -eolc launcher.edl &
