#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2006-2007 Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# Wrapper for automatically building NTP server.

set -e

: "${BUILD_ARCHS:?Need to specify a build architecture}"

VERSION=4.2.2p3
# Name of tgz file containing NTP distribution
TAR_FILE=ntp-$VERSION.tar.gz
# Name of NTP directory extracted from distribution
NTP_DIR=ntp-$VERSION
# Location on host system of NTP distribution
TAR_DIR=/dls_sw/prod/targetOS/tar-files/

cd "$(dirname "$0")"
HERE="$(pwd)"
INSTALL_DIR="$HERE/install"

# Figure out where the cross-compiler is.  We do this by asking the EPICS
# makefile, which certainly knows!
GNU_DIR="$(
    cd "$HERE/../.."
    make -pn BUILD_ARCHS="$BUILD_ARCHS" 2>/dev/null |
    sed -n '/^GNU_DIR = /{s///;p;q;}')"
export PATH="$PATH:$GNU_DIR/bin"

GNU_TARGET="$(
    cd "$HERE/../.."
    make -pn BUILD_ARCHS="$BUILD_ARCHS" 2>/dev/null |
    sed -n '/^GNU_TARGET = /{s///;p;q;}')"

echo GNU_DIR="$GNU_DIR"
echo GNU_TARGET="$GNU_TARGET"

if [ -z "$GNU_DIR" -o -z "$GNU_TARGET" ]; then
    echo Couldn\'t set up environment
    exit 1
fi

# Build everything
rm -rf "$BUILD_DIR"  &&
tar xzf "$TAR_DIR/$TAR_FILE"  &&
cd "$NTP_DIR"  &&
./configure --host=$GNU_TARGET --disable-all-clocks --disable-parse-clocks  &&
make  || {
    echo Error building ntpd >&2
    exit 1
}

# Place where required
rm -rf "$INSTALL_DIR" &&
mkdir -p "$INSTALL_DIR/etc/init.d" "$INSTALL_DIR/usr/sbin"  &&
cd "$HERE"  &&
cp "$NTP_DIR/ntpd/ntpd" "$INSTALL_DIR/usr/sbin"  &&
cp "install-ntpd"       "$INSTALL_DIR"  &&
cp "ntpd"               "$INSTALL_DIR/etc/init.d"  &&
cp "ntp.conf"           "$INSTALL_DIR/etc"  
