#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2006-2007 Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# Wrapper for automatically building NTP server.

VERSION=4.2.2p3
TAR_FILE=ntp-$VERSION.tar.gz

TAR_DIR=/scratch/incoming

HERE="$(dirname "$0")"
TOP="$HERE/../.."

BUILD_DIR="$HERE/../ntp-$VERSION"
INSTALL_DIR=/home/libera/nfs/install/ntp


# Figure out where the cross-compiler is.  We do this by asking the EPICS
# makefile, which certainly knows!
GNU_DIR="$(
    cd "$TOP"
    make -pn 2>/dev/null |
    sed -n '/^GNU_DIR = /{s///;p;q;}')"

export PATH="$PATH:$GNU_DIR/bin"

rm -rf "$BUILD_DIR"

# Build everything
cd "$HERE"  &&
tar xzf "$TAR_DIR/$TAR_FILE"  &&
cd "$BUILD_DIR"  &&
./configure --host=arm-linux --disable-all-clocks --disable-parse-clocks  &&
make  || {
    echo Error building ntpd >&2
    exit 1
}

# Place where required
rm -rf "$INSTALL_DIR" &&
mkdir -p "$INSTALL_DIR/etc/init.d" "$INSTALL_DIR/usr/sbin"  &&
cp "$BUILD_DIR/ntpd/ntpd" "$INSTALL_DIR/usr/sbin"  &&
cp "$BUILD_DIR/install-ntpd" "$INSTALL_DIR"  &&
cp "$BUILD_DIR/ntpd" "$INSTALL_DIR/etc/init.d"  &&
cp "$BUILD_DIR/ntp.conf" "$INSTALL_DIR/etc"  
