#!/bin/sh

# Start and stop ntp daemon

. /etc/init.d/functions
. /etc/sysconfig/clock


case "$1" in
    start)
        echo -n Starting ntpd
        ntpd -g
        evaluate_retval
        ;;
    stop)
        echo -n Stopping ntpd
        kill "$(cat /var/run/ntpd.pid)"
        evaluate_retval
        ;;
    restart)
        "$0" stop
        "$0" start
        ;;
    *)  echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac