#!/bin/sh

# Script to check for undocumented PVs.

TEMP_ROOT="$(mktemp -d /tmp/check-pv-docs.XXXXXX)"
trap 'rm -rf "$TEMP_ROOT"' EXIT

LIBERA="$(cd "$(dirname "$0")"/..; pwd)"

# Get the list of all generated PVs
cat "$LIBERA"/db/*.db |
sed -nr '/^record/{s/^[^"]*"\$\(DEVICE\)://; s/".*$//; p;}' |
# Filter out a number of special cases
sed -r '
    /^..:MC(H|L)$/{/^CK/!d}     # :MCH, :MCL except for CK
    /^.*TRIG$/d                 # Trigger
    /^.*DONE$/d                 #   and done records
    /^.*TRIGFAN.*$/d            # Trigger and
    /^.*FANOUT[0-9]*$/d         #   normal fanout records
    /^.*_C$/d                   # In-Out
    /^.*_R$/d' |                #  loopback records
sort >"$TEMP_ROOT"/pvs.txt

# Extract a list of all documented PVs
cat "$LIBERA"/docs/libera.txt |
sed -nr '
    # Each group is headed by a line of the form <group> = XX
    /^.*<group> = (..).*:/{
        s//\1/
        h
    }
    # Each PV documentation set consists of a line of comma separated PV
    # descriptions with the line ending in ::
    1,/\(no group\):$/{
        /::$/{
            s///                    # Discard the ::
            T
            s:^// ::                # Allow for asciidoc comments
#            \:^//:d                 # Ignore asciidoc comments
            s/`//g                  # Discard the ` characters
        :1
            # This loop adds the group identification in front of each PV
            G                       # Pull group from hold space
            s/^(.*)\n(..)$/\2:\1/   # Move to start of line
            T                       # Skips lines before first group
            s/, /\n/                # Split line at next ,
            P                       # And print it
            T                       # If no , then we are done
            s/^[^\n]*\n//           # Otherwise delete line just printed
            b1                      # and carry on.
        }
    }
    # When we reach the no group section we need to treat this specially.
    # Fortunately no line splitting tricks needed.
    /\(no group\):/,${
        /::$/{
            s///
            s/`//g
            p
        }
    }' |
# Expand the special PV patterns.  These are all documented in libera.txt.
sed -r '
    /^(.*)<channel>(.*)$/s//\11\2\n\12\2\n\13\2\n\14\2/
    /^(.*)<iq>(.*)$/{
        s//\1AI\2\n\1AQ\2\n\1BI\2\n\1BQ\2\n\1CI\2\n\1CQ\2\n\1DI\2\n\1DQ\2/}
    /^(.*)<buttons>(.*)$/s//\1A\2\n\1B\2\n\1C\2\n\1D\2/
    /^(.*)<positions>(.*)$/s//\1X\2\n\1Y\2\n\1Q\2\n\1S\2/
    /^(.*)<fan>(.*)$/s//\11\2\n\12\2/
    /^(.*)<1-8>(.*)$/{
        s//\11\2\n\12\2\n\13\2\n\14\2\n\15\2\n\16\2\n\17\2\n\18\2/}
    /^(.*)<link>(.*)$/{
        s//\1LINK1\2\n\1LINK2\2\n\1LINK3\2\n\1LINK4\2/}
    ' |
sort >"$TEMP_ROOT"/docs.txt

# comm "$TEMP_ROOT"/pvs.txt "$TEMP_ROOT"/docs.txt
diff "$TEMP_ROOT"/pvs.txt "$TEMP_ROOT"/docs.txt |
sed -rn '/^<|^>/p'
