#!/bin/sh

# This file is part of the Libera EPICS Driver,
# Copyright (C) 2005  Michael Abbott, Diamond Light Source Ltd.
#
# The Libera EPICS Driver is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.
#
# The Libera EPICS Driver is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General
# Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc., 51
# Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Contact:
#      Dr. Michael Abbott,
#      Diamond Light Source Ltd,
#      Diamond House,
#      Chilton,
#      Didcot,
#      Oxfordshire,
#      OX11 0DE
#      michael.abbott@diamond.ac.uk

# Where to find the upgrade files
UPGRADES_DIR=/mnt/nfs/install

# Server providing rdate functionality
RDATE_SERVER=172.23.199.1


# These files are overwritten by the upgrade process, but need to be
# preserved. 
SAVE_FILES="network libera nic-config/ifcfg-eth0"

cd /
hostname

# Bring the libera into a sensible quiescent state suitable for applying the
# upgrades
rdate -s $RDATE_SERVER
[ -e /etc/init.d/epics ] && /etc/init.d/epics stop
/etc/init.d/libera stop

# Put the saved files to one side
for file in $SAVE_FILES; do
    mv /etc/sysconfig/$file /etc/sysconfig/$file.dls
done

# Perform all the required upgrades
for name in $(ls "$UPGRADES_DIR"/upgrade-$1/upgrade/*.lpm); do
   echo $name
   /opt/bin/libera_upgrade $name
done

echo "serv0005.cs.diamond.ac.uk:/home2/libera/nfs /mnt/nfs nfs rw,rsize=4096,wsize=4096" >>/etc/fstab
echo "TIMESERVER=$RDATE_SERVER" >/etc/sysconfig/clock
ln -sf /bin/false /sbin/dhcpcd

for file in $SAVE_FILES; do
    mv /etc/sysconfig/$file.dls /etc/sysconfig/$file
done
